### ISSUE TITLE
Improve line/arrow drawing (color, dash, polyline, etc.)

### ISSUE THREAD

**Issue by fbahoken** [riatelab/magrit#103]
In the section "Layout and page setup": give the possibility to draw a straight line (solid or dashed) to indicate a separation. 
Example a line between France and Corse if it has been moved to the continent.

**Comment by fbahoken** [comment]
Proposal: add a direction option (e.g. by a checkbox: add an arrow) to the existing option to draw an arrow.

Alternatively, add a new possibility to draw a line on the map layout.

**Comment by fbahoken** [comment]
That's exactly right !

A single line could have been enough, but if we can make a polyline, it's even better.

I'm afraid, I didn't see the option to hide the arrowhead ?! ...

**Comment by fbahoken** [comment]
Yes, of course. Thank you very much :)

**Comment by mthh** [comment]
I have taken the liberty of renaming the issue to better reflect (I hope) what was discussed / what was asked, namely
- enable drawing polylines
- enable the line to be dashed/dotted

To which I add :
- enable changing the color of the line / arrow

**Comment by mthh** [comment]
New lines are actually polylines and are customizable (thickness, color, opacity, dashed or not, arrow head or not).
