### ISSUE TITLE
Add legend for label layers

### ISSUE THREAD

**Issue by fbahoken** [riatelab/magrit#107]
Hello Mathieu,

please, allow us the possibility to add a legend to labels layers.

![magrit_issues_legend_labels](https://user-images.githubusercontent.com/13615192/225672328-2112891f-0ebf-4a2e-aac3-7a1007689919.PNG)

This is useful when :
 1) different levels of labels are displayed (e.g capitals, main cities, other cities) or
 2) a filter is applied on the labels (e.g. only places with more than x variable are mentioned). 

Thank you very much :-)

**Comment by mthh** [comment]
Hello @fbahoken,

Thank you for the suggestion.

Practically speaking, what shape would you like this legend to take, in particular for your 2nd use case ? (don't hesitate to provide a quick drawing or a screenshot of a similar legend if its simpler than explaining it with words !)

Thx !

**Comment by fbahoken** [comment]
Hello Mathieu,

I'll break down the subject of labels, with images, it will be easier.

**First of all, about the labeling on the map.**

- label placement is "OK" for classic proportional symbols (in yellow)
![label_simple](https://user-images.githubusercontent.com/13615192/225901917-c2502fd7-f377-4bee-b4bc-3f938e425601.PNG)

- label placement is not OK for dorling proportional symbols (in orange) : the labels are not "dorling moved" as the symbols
![label_dorling](https://user-images.githubusercontent.com/13615192/225901925-14337108-45fc-43ec-9d5d-33c72feea25a.PNG)

- The display of fields, on mouse-over of the tooltip [i] does not work for dorling symbols (it is OK for classic proportional symbols)

![survol_1](https://user-images.githubusercontent.com/13615192/225902220-c8b3e615-4341-49c1-b400-5921239d7730.png)

**Comment by fbahoken** [comment]
When a filter is applied on a label layer, following are the 2 problems mentionned previously.

**(1) It is (apparently) not possible to add the label layer as a legend element**, in order to indicate why this selection of label is on the map (especially the reason of filtering).
Hereby, the blue mention "Madrid... has been added manually

![legend_for_labels](https://user-images.githubusercontent.com/13615192/225907612-1afe45c2-dcc5-40a7-bf8d-bcf85445bbf9.png)

</br>
(2) **This error message appears when clicking on the legend icon** of a label layer (apparently for any label layer)

![legend_for_labels_2](https://user-images.githubusercontent.com/13615192/225907879-cba231b5-0074-44bd-ab43-b897eea7ed0e.png)

</br>

Thank you very much

**Comment by mthh** [comment]
> When a filter is applied on a label layer, following are the 2 problems mentionned previously.
> 
> **(1) It is (apparently) not possible to add the label layer as a legend element**, in order to indicate why this selection of label is on the map (especially the reason of filtering). Hereby, the blue mention "Madrid... has been added manually
> 
> ![legend_for_labels](https://user-images.githubusercontent.com/13615192/225907612-1afe45c2-dcc5-40a7-bf8d-bcf85445bbf9.png)
> 
> 
> (2) **This error message appears when clicking on the legend icon** of a label layer (apparently for any label layer)
> ![legend_for_labels_2](https://user-images.githubusercontent.com/13615192/225907879-cba231b5-0074-44bd-ab43-b897eea7ed0e.png)
> 
> 
> Thank you very much

Based on your first message and on your last message it looks like there is only one issue in the end : there is just no legend for label layers in Magrit.
We will add this possibility in a future release.

**Comment by fbahoken** [comment]
Thank you very much

**Comment by mthh** [comment]
> * label placement is not OK for dorling proportional symbols (in orange) : the labels are not "dorling moved" as the symbols

I have opened its own issue for this problem (#108).

> * The display of fields, on mouse-over of the tooltip [i] does not work for dorling symbols (it is OK for classic proportional symbols)
> 

I encounter no problem to display the info box for dorling symbols. As with other layer layers, the layer have to be on top (and you have to deactivate/reactivate it if it was already enabled when you computed a new representation - this last point could probably be improved).

**Comment by mthh** [comment]
> Thank you very much

Thanks for the reminder, I believe the message "Want to make a suggestion ?" is here since a few years when asking for a legend on the label layer but you're the first to reach about about this !

**Comment by fbahoken** [comment]
> > * label placement is not OK for dorling proportional symbols (in orange) : the labels are not "dorling moved" as the symbols
> 
> I have opened its own issue for this problem (#108).
> 
> > * The display of fields, on mouse-over of the tooltip [i] does not work for dorling symbols (it is OK for classic proportional symbols)
> 
> I encounter no problem to display the info box for dorling symbols. As with other layer layers, the layer have to be on top (and you have to deactivate/reactivate it if it was already enabled when you computed a new representation - this last point could probably be improved).

Yes ! I saw that case in the meantime. The demers labels layer have to be placed on the top ! It is OK for me now.

**Comment by mthh** [comment]
I implemented the legend for label layers on my [features/legend-for-labels](https://github.com/mthh/magrit/tree/features/legend-for-labels) branch.
By default it displays the name of the first entity (respecting the style of the labels), a colon, the name of the layer and then the name of the field between parentheses. It also displays the value of the filter if any. 
Cf. the following screenshot :

![label-layer-legend](https://user-images.githubusercontent.com/12172162/227462298-3e447e58-a0ab-417e-937a-2d7b414aa366.png)

All these textual values can be modified manually for a better result (see the video below).

https://user-images.githubusercontent.com/12172162/227462211-49d4855a-cf5e-4040-ae65-43ea31bc24c7.mp4


I will probably merge it on magrit main branch then publish a new version (0.14.0) latter today.

**Comment by mthh** [comment]
Merged and published.
The new version (0.14.0) will be made available during the night on https://magrit.cnrs.fr/.

**Comment by fbahoken** [comment]
Super ! C'est parfait. Merci beaucoup @mthh
