### ISSUE TITLE
Problème Carte Lissée 

### ISSUE THREAD

**Issue by ydidees** [riatelab/magrit#112]
Bonjour,

J'ai rencontré un problème avec le module de lissage spatial. 
Je souhaiterais faire des cartes lissées avec la même discrétisation. Les variables dans les mêmes fond de carte/données importées dans Magrit. Quand je lance un lissage (span = 15 km, beta = 2, fonction exponentielle) avec 8 classes (automatiques), la carte lissée sort bien. En revanche, quand je mets des limites de classes manuelles, cela ne fonctionne plus (message : "Erreur ! Une erreur s'est produite - L'opération en cours a été stoppée"). J'ai essayé en mettant les mêmes classes que celles obtenues avec un lissage "automatique", et j'obtiens la même erreur.
En fait, selon les bornes de classes que j'indique, j'ai le message d'erreur ou non. Je ne comprends pas d'où cela peut venir.
J'ai joint un fichier PDF avec les 3 imprim' écrans des cas de figures rencontrés, avec le paramétrage sur la gauche pour que vous puissiez comparer.

Merci pour votre aide !
[Error_Smoothing.pdf](https://github.com/riatelab/magrit/files/11159390/Error_Smoothing.pdf)

**Comment by mthh** [comment]
Bonjour @ydidees et merci pour votre retour.
Ce n'est effectivement pas normal, je vais investiguer et je reviens vers vous rapidement !

**Comment by ydidees** [comment]
Super, merci beaucoup !
J'ai fait plein de tests avant de vous contacter, et vraiment des fois ça marche, des fois ça ne marche pas (selon les bornes manuelles choisies). Comme une lissée arrive à être calculée par un lissage sans bornes manuelles, ne vient pas a priori pas des données (j'ai bien vérifiée qu'il n'y ait que des valeurs numériques).

**Comment by mthh** [comment]
C'est effectivement très probable que le problème vienne de la gestion par Magrit des bornes manuelles.

J'ai essayé sur plusieurs jeux de données mais je n'ai pas réussi à reproduire le problème.
Pourriez-vous ouvrir les outils de développement, vous rendre dans la console (F12 sur Firefox ou Chrome, puis onglet "console") et m'envoyer une copie de l'erreur qui devrait y apparaître ? (cf. la partie droite de mon screenshot - ici sans erreur)

![magrit-devtools](https://user-images.githubusercontent.com/12172162/230159890-ad944b9f-5c4e-48fb-84a6-8742882b5165.png)

Et/ou accepteriez-vous de m'envoyer votre jeu de données afin que je puisse reproduire l'erreur et identifier le problème en saisissant les mêmes valeurs que vous ? (dans ce cas vous pouvez me le transmettre à l'adresse matthieu.viry@cnrs.fr)

**Comment by ydidees** [comment]
Merci !
Ci-joint la copie de l'erreur. Il y a 3 screenshot car tout ne rentrait pas dans l'écran.

[Copie_Erreur.pdf](https://github.com/riatelab/magrit/files/11162576/Copie_Erreur.pdf)

**Comment by mthh** [comment]
Merci beaucoup pour votre capture d'écran !

Ça m'a permis d'identifier le problème, qui est double :
- un problème avec la gestion des géométries nulles / vides (réintroduit récemment, et que j'ai corrigé dans bb87bd9 et 6782582 mais qui n'a pas encore été mis en ligne sur magrit.cnrs.fr) et qui correspond aux messages présents dans la console sur votre capture d'écran, lui même même causé par
- un problème dans la gestion des bornes par Magrit (en particulier concernant la gestion de la limite inférieur de la première classe).

Je vais corriger ces différents éléments, une nouvelle version devrait être en ligne demain matin.

En attendant, je pense que vous pouvez remplacer la limite inférieure de votre première classe (0.78 dans votre exemple) par une valeur plus petite (0.7 ou 0.6 par exemple). Cette valeur devrait être remplacée par la vraie valeur minimale dans la couche de résultat que vous sera renvoyée.

**Comment by ydidees** [comment]
Merci beaucoup ! Je teste cela demain et vous tiens au courant.

**Comment by mthh** [comment]
Super, merci !

**Comment by mthh** [comment]
Corrigé dans bb87bd9 et c905345 et publié dans la version 0.15.0 (confirmation par e-mail que le problème est bien résolu).
