### ISSUE TITLE
Projection Bertin 1953

### ISSUE THREAD

**Issue by CatProdig** [riatelab/magrit#114]
Bonjour,
Je souhaiterai utiliser la projection Bertin 1953 dans une application comme Arabesque, vous serait-il possible de me fournir le code en proj4 de cette projection telle qu'elle est représentée dans Magrit. Merci

**Comment by mthh** [comment]
Bonjour,

Magrit utilise la projection Bertin 1953 issues de d3-geo-projection ([ici](https://github.com/d3/d3-geo-projection#geoBertin1953)) mais la projection Bertin 1953 n'est pas supportée par la bibliothèque [proj4.js](https://github.com/proj4js/proj4js) qui est utilisée par Magrit en complément de d3 (bien qu'elle soit supporté depuis quelques années depuis la bibliothèque Proj - cf. [ici](https://proj.org/operations/projections/bertin1953.html) - depuis laquelle est portée Proj4.js).

En conséquence, utiliser le code proj4 de la projection Bertin (qui est "+proj=bertin1953" d'après [la documentation de Proj](https://proj.org/operations/projections/bertin1953.html)) ne fonctionne pas dans Magrit (et il faut donc choisir directement cette projection depuis le menu des projections comme vous avez pu le voir).

Je ne sais pas comment sont gérée les projections dans Arabesque mais je vous conseille de voir directement avec les développeurs de cette application (par exemple sur leur repository GitHub ici : https://github.com/gflowiz/arabesque).

**Comment by mthh** [comment]
Je clos cette issue mais n'hésitez pas à la rouvrir (ou à en ouvrir une autre) si besoin.
