### ISSUE TITLE
Problème lors de la création d'une palette personnalisée

### ISSUE THREAD

**Issue by ElinaMX** [riatelab/magrit#117]
Les couleurs personnalisées ne s'enregistrent pas, ne sont pas prises en compte à l'enregistrement de la palette, ni dans l'histogramme, ni au moment de "dessiner le résultat". 

Il est impossible de "sortir" du menu de personnalisation de couleur sans enregistrer de palette (pas de bouton de fermeture de fenêtre) 

![Capture d’écran 2023-07-12 170046](https://github.com/riatelab/magrit/assets/95742383/41387c79-a0bd-4b6a-9922-c42106ac0ded)

**Comment by mthh** [comment]
Merci, je vais corriger ça, et je ferais surement une nouvelle release ce soir ou demain si tout se passe bien (pour info., la version sur magrit.cnrs.fr est mise à jour automatiquement toutes les nuits après qu'une nouvelle release ait été faite).

**Comment by mthh** [comment]
I've fixed the bug: the colors defined in the custom palette are now taken into account in the histogram and then on the map. Thanks for the bug report!

I've also added a "cancel" button when defining the custom palette. As a reminder (in case of future bugs, as the code is very messy in this part of the interface ;)) the logic I've implemented is as follows: if the user clicks on "cancel" and there isn't already a custom palette available for the current number of classes, we return to the "sequential palette" part of the discretisation panel; if the user clicks on "cancel" and there is a custom palette (or palettes) available for this number of classes, then the first of these is selected.

I've also improved a bit the sizes of the `input` element for entering the name of the new palette and the `select` element for selecting custom palettes.

![pal1](https://github.com/riatelab/magrit/assets/12172162/c1749077-7cf8-4d7b-a4fd-0c7be8b44ab0)

![pal2](https://github.com/riatelab/magrit/assets/12172162/9c35c481-0346-4f03-9447-680856982cd3)

![pal3](https://github.com/riatelab/magrit/assets/12172162/4263cc6d-7b5c-447e-a5ca-157a366c5679)
