### ISSUE TITLE
Add the documentation to master branch

### ISSUE THREAD

**Issue by ArmelVidali** [riatelab/magrit#121]
Hi,

I'm working on a custom version of your documentation available on https://magrit.cnrs.fr/static/book/ , I'd like to add content to explain the modifications I made on my local magrit.

Could you please add it to the master so that I can reuse it ?

Armel

**Comment by mthh** [comment]
Hello Armel,

The documentation source is already tracked on the master branch. You can find the source in the `documentation` folder ([here](https://github.com/riatelab/magrit/tree/master/documentation)) :
- the `book.toml` is the configuration file (it specifies where to put the built documentation, its title, etc.),
- the `src` folder contains all the Markdown files (one per page of the documentation) and some images,
- the `src/SUMMARY.md` file is used to specify which pages should appear in the documentation, in which order, etc.

It is all written in Markdown and it is compiled to HTML using [mdBook](https://rust-lang.github.io/mdBook/) (which puts the result in the in the `static/book` folder, as you saw - but our users usually access it by the URL https://magrit.cnrs.fr/docs/).

To compile the documentation, we run the command `mdbook build` in the `documentation` folder.

Hope this helps.

**Comment by ArmelVidali** [comment]
Thanks very much ! I wasn't looking at the right folder
