### ISSUE TITLE
Bad message wording when rows missing in dataset

### ISSUE THREAD

**Issue by asitemade4u** [riatelab/magrit#123]
When joining a basemap and a dataset I get the message:

![2024-02-14_15-17](https://github.com/riatelab/magrit/assets/11460106/edc2dd61-1b74-400a-bd55-6364fd7c34d8)

Which is not relevant.
One should possibly say:

_The values on which to operate have to be unique._

Besides, it would be helpful to have a log of the duplicate rows.

**Comment by mthh** [comment]
> I am having a blast with Magrit, which is a great program.

Nice to read this, thanks :)

> BTW, being French and living in the U.S. I am happy to help you with any translation...

I'm taking note of your suggestion!
If you're interested we'll let you know when we'll be making a beta of the new version available (in a few months' time), if you're available then, I'm sure you'll have some good suggestions for us in that area!
