### ISSUE TITLE
Implement head/tails classification

### ISSUE THREAD

**Issue by asitemade4u** [riatelab/magrit#124]
Hi,
Fisher/Jenks algorithm is generally considered the most usual, and as such has been adopted by most cartographic tools as their default when drawing choropleth maps.
However, Head/Tails algorithm (Bin Jiang, 2011) has a lot of advantages, notably when depicting heavy-tailed distributions -- which is what I am dealing with in immigration demographics in NYC.
Would you implement it in Magrit?

Thank you,
S.

**Comment by mthh** [comment]
Hi,

Thanks for the suggestion. I also think that this is a useful classification method that should be added.
It's already present in the future version of the application that I mentioned in a previous message (although we don't plan to backport it to the current branch).
