### ISSUE TITLE
Issue data view

### ISSUE THREAD

**Issue by mmaeght** [riatelab/magrit#125]
Good afternoon, 

When uploading my data, the venture went well, and I can see all my data in the table. However, it appears that when I create the layer corresponding to "ratio", only a part of the data is visible. It is all the most weird as I can see in the layer settings that these data were taken into account. The population is '13' + 12 data non available, which makes 25 that is my whole population. However, when looking at the map, there are only 6 regions which are colored. 

Does anyone know the reason of this mistake? An idea to solve it? 

I've tried to redo it, to change the data set, try with other layers ... but nothing works and it is always the same regions which are not colored... 

Thank you in advance for your help! 

<img width="1315" alt="Sugarbeet_production_2022" src="https://github.com/riatelab/magrit/assets/164029893/254df8bb-623f-41f8-8f18-db60d5d2895f">
<img width="846" alt="Capture d’écran 2024-03-19 à 14 49 12" src="https://github.com/riatelab/magrit/assets/164029893/cb6601ed-fe92-4044-9acb-79977f5a6aaa">
<img width="867" alt="Capture d’écran 2024-03-19 à 14 53 47" src="https://github.com/riatelab/magrit/assets/164029893/d38cca33-7a76-4215-b1ac-a55be68eeca2">

**Comment by mthh** [comment]
Thank you for your interest in Magrit and for your bug report.

It's weird indeed...!
Could you share your dataset so that I can investigate whether it's a problem with our classification method or the application of colours on the basis of the classification? (this is a problem we've never encountered before)
If so you can send it to matthieu.viry@cnrs.fr (I'm the developer/maintainer of Magrit) and I could take a look at it tomorrow.

**Comment by mthh** [comment]
To add further information to this problem: the Ukraine base map comes from [Cartography Vectors](https://cartographyvectors.com/map/1530-ukraine-with-regions) and seems to be at fault in this issue.

Several geometries appear to be invalid (according to GEOS and QGIS methods), but other (valid according to GEOS/QGIS) geometries fail to be colored correctly in Magrit, which should not happen and is still under investigation.

We also note that generalizing geometries (e.g. in MapShaper) and/or passing through GEOS make_valid seem to correct the problems.

In addition, several Cartography Vectors datasets seem to present significant topology issues (for example, the [Paris](https://cartographyvectors.com/map/552-paris) dataset, in which districts sometimes overlap, or there are gaps between them).
