### ISSUE TITLE
Carte de liens : impossibilité logique ?

### ISSUE THREAD

**Issue by charbonnerie** [riatelab/magrit#126]

**Comment by mthh** [comment]
Bonjour,

> L'interface d'importation d'un jeu de données impose que la première colonne ne contienne que des données unique : c'est incompatible avec la création de carte de liens qui implique des paires multiples, comme dans l'exemple fourni d'ailleurs dans le manuel en ligne.

Je pense que vous parlez ici de la fenêtre de jointure des données (qui exige en effet que les identifiants soient uniques - c'est nécessaire pour pouvoir réaliser la jointure sans ambiguités, comme dans l'exemple ici : https://magrit.cnrs.fr/docs/import/jointure_fr.html).

Toutefois dans votre cas il n'est pas nécessaire d'effectuer une jointure (à proprement parler, ou en tout cas tel qu'entendu par Magrit) entre votre jeu de données géographiques et votre jeu de données tabulaires : vous pouvez directement aller sur la fonctionnalité "Liens", choisir les colonnes de votre CSV qui correspondent aux départements d'origine, aux départements de destinations et à l'intensité du liens entre origine et destination.

> Typiquement, pour réaliser une carte qui permet de visualiser la fréquence de mariages inter-départementaux, il faut répliquer un département donné autant de fois qu'il existe de cas de mariages avec d'autres départements :

En effet, c'est d'ailleurs la structure du fichier fourni en exemple dans la documentation (ou les identifiants sont répétés aussi bien dans le champ origine que dans le champ destination).

Je peux vous envoyer une courte vidéo de démonstration si vous le souhaitez.

**Comment by charbonnerie** [comment]
Bonjour,
Je vous remercie pour votre réponse rapide. Entre-temps, j’avais trouvé une méthode de contournement de la difficulté, mais elle m’impose de beaucoup trafiquer mon fichier de données.
Je suis donc bien volontiers preneur de votre proposition de vidéo de démonstration.
Bien cordialement,
Youssef Guiga

**Comment by mthh** [comment]
Ci-joint une vidéo présentant le déroulé : 

- Import du fond de carte géographique (lors du typage des champs, mettre le champ d'identifiant avec le type "Identifiant")
- Import du fichier tabulaire (lorsque Magrit demande si on souhaite effectuer la jointure maintenant il faut répondre "Non")
- Sélection de la fonctionnalité "Liens" et des paramètres appropriés (les champs origines, destination et intensité du fichier CSV ; "i", "j" et "fij" dans mon cas) et le champs d'identifiants du fichier géo ("N0" dans mon cas). Notez que les valeurs présentes dans les champs "origine" et "destination" doivent avec des correspondances avec les identifiants présents dans le fichier géo pour que cela fonctionne).


[Demo-links.webm](https://github.com/riatelab/magrit/assets/12172162/028c3dd5-d182-4217-bb5f-88c42458e71f)

**Comment by charbonnerie** [comment]
Merci beaucoup !
Jamais je n’aurais trouvé cela tout seul.
Bien à vous,
Youssef Guiga

**Comment by mthh** [comment]
Je vous en prie.

Nous allons sortir une nouvelle version de Magrit d'ici quelques mois ; nous veillerons à être plus explicite à propos de ces différents aspects dans la nouvelle documentation.

N'hésitez pas à ouvrir une nouvelle issue ici si vous rencontrez un nouveau problème !

**Comment by charbonnerie** [comment]
Bonjour,
Avec le passage à la version V2, je ne retrouve plus la fonctionnalité qui permet d’ajouter des étiquettes. Pourriez-vous m’indiquer où se trouve désormais cette possibilité dans la nouvelle interface ?
Par avance, je vous en remercie.
Cordialement,
Youssef Guiga

**Comment by mthh** [comment]
Bonjour,

Dans la v2 la fonctionnalité d'ajout d'étiquettes est considérée comme un mode de représentation à part entière, il faut donc créer la couche d'étiquette comme n'importe quelle autre représentation (cf. également le gif ci-dessous) : 
- clic sur la cible de la couche à utiliser pour créer les labels,
- choix de la fonctionnalité "Étiquette" (c'est la 3ème fonctionnalité dans la liste),
- création de la couche.

![Image](https://github.com/user-attachments/assets/a6df002a-33e4-44f0-9986-21fc45730540)

Notez qu'il est désormais possible de mieux personnaliser les couches d'étiquettes : choix de la police d'écriture, décalage en X, décalage en Y, halo autour du texte, possibilité de les déplacer manuellement, etc.

**Comment by charbonnerie** [comment]
Bonjour,
Merci beaucoup pour votre réponse rapide (un dimanche 🤭) et votre aide efficace : ça fonctionne très bien.
Bon après-midi.
Cordialement,
Youssef Guiga

**Comment by charbonnerie** [comment]
Bonjour,
Je reviens vers vous, car je ne retrouve pas le fichier json des départements qui permet de superposer le jeu de données « communes » issu de Magrit avec les limites des départements. Ou bien peut-être existe-t-il une autre méthode pour obtenir ce résultat ? Voir exemple en pièce jointe.
Par avance, je vous remercie de l’aide que vous voudrez bien m’apporter.
Cordialement,
Youssef Guiga

**Comment by mthh** [comment]
Bonjour,

En effet ce fond de carte "département" adapté à notre fond de carte "commune" n'est pas proposé dans la fenêtre des jeux de données d'exemple car il est possible de le créer en réalisation une agrégation du jeu de données "commune" en utilisant le champ "DEP" (l'opération est similaire à l'outil "dissolve" de QGIS par exemple).

Cf. la vidéo d'illustration ci-dessous :

https://github.com/user-attachments/assets/7a0ed824-a684-4ef7-8713-4552b7c4410d

En espérant que ça réponde à votre question !

**Comment by charbonnerie** [comment]
Merci beaucoup pour votre réactivité. Entre temps, j’ai retrouvé comment j’avais procédé la fois précédente : en réutilisant le « template cartographique » intitulé « Communes de France (modèle cartographique) ». Mais je vais néanmoins explorer la fonctionnalité d’agrégation, qui pourra m’être utile pour d’autres besoins.
Bien à vous,
Youssef Guiga
