### ISSUE TITLE
Use of $length for number of elements 

### ISSUE THREAD

**Issue by RCura** [riatelab/magrit#130]
After reading the full documentation on field computation, I'm wondering wether the use of the `$length` variable is the more fitting for refering to the number of features of a layer.

While `$area` is used both on Magrit SQL and QGIS SQL, `$length` refers to line geometrical length in QGIS, and I fear that the use of this exact same variable might confuse the (few, thats right) users that would use both QGIS and Magrit .

Maybe something like $count (not that much satisfying indeed) could instead be used ?

**Comment by mthh** [comment]
Good idea! I will change `$length` to `$count` (and maybe one day use $length for something else like line length).

**Comment by mthh** [comment]
While working on this I've also noticed that the tooptip for these 3 special fields wasn't working, so I'm fixing that as I go.
