### ISSUE TITLE
Importation d'un fond de carte

### ISSUE THREAD

**Issue by DAVIDGOUARD** [riatelab/magrit#138]
Bonjour,
Sur la V2 de Magrit, je ne parviens pas à importer un fond de carte. Quelle est la manipulation svp ?
Merci

Bien à vous

**Comment by DAVIDGOUARD** [comment]
Merci pour votre réponse. J'avais tenté de réaliser ces deux démarches, mais je crois que le problème vient du fond de carte. 
![copie écran fichiers de cartes](https://github.com/user-attachments/assets/65004792-b65a-4ded-bcf7-209e0f9eb30e)
J'ai tenté de mettre en copie d'écran en PJ ici, mais manifestement cela ne marche bien, ou bien il s'agit d'un langage dépassant mes compétences. 
Il s'agit du fond de carte des 25 bureaux de vote de la ville de Colomiers. Magrit ne reconnait pas le fichier. J'ai pourtant pris le format shp

Bien à vous
![copie écran fichiers de cartes](https://github.com/user-attachments/assets/2abd6fe1-a9c9-458d-a2f9-0ef7536c8d61)

**Comment by DAVIDGOUARD** [comment]
Le lien source est ici : https://data.haute-garonne.fr/explore/dataset/bureaux-de-vote-haute-garonne-2022-insee/export/?refine.commune_nom=Colomiers&location=22,43.6098,1.32962&basemap=jawg.streets

**Comment by mthh** [comment]
Dans le cas d'un fichier zip (contenant des shapefile), il faudrait que vous dézippier les différents fichiers avant de les importer, c'est peut-être ça qui pose problème.

Ci-joint un détail des étapes à suivre sur Windows : 

1) Télécharger le jeu de données que vous avez indiqué 

2) Décompresser les fichiers en faisant un clic-droit puis en appuyant sur "Extraire tout..." :

<img width="960" alt="extraire-tout" src="https://github.com/user-attachments/assets/8567a344-693e-4389-bbf0-8aa549d7ef4c">

3) Ouvrir la fenêtre d'import des données de Magrit (en cliquant sur "Ouvrir la fenêtre d'import des données..."), cliquer sur "Ouvrir" et sélectionner l'ensemble des fichiers décompressés :

<img width="960" alt="selection-fichiers" src="https://github.com/user-attachments/assets/4b8eb44d-bc99-4afa-aedb-36c59ff055b9">

4) Vous devriez alors voir le fichier dans la liste :

<img width="960" alt="apres-selection" src="https://github.com/user-attachments/assets/19a5688a-c002-44bb-92c4-dc078bcf150c">

5) Vous pouvez alors cliquer sur "Importer le jeu de données" en bas de la fenêtre, les données vont alors s'afficher et la carte doit se centrer automatiquement sur le jeu de données qui vient d'être importé si c'est le premier jeu de données qui est importé dans le projet actuel :

<img width="960" alt="all-done" src="https://github.com/user-attachments/assets/9f59154a-9bd7-4f5d-adae-cb303ac0e72e">

**Comment by mthh** [comment]
Je ferme cette issue car ça semble être OK mais n'hésitez pas à la rouvrir en cas de soucis.

**Comment by DAVIDGOUARD** [comment]
Bonjour,
Un ami, Stéphane, m'a dit que le fichier ne convenait pas car il ne s'agit pas de polygones géométriques mais de points correspondants à l'adresse des bureaux de vote. Il a réussi à m'adresser un nouveau jeu de données avec les bureaux de vote en polygones géométriques (voir PJ), mais je me rends compte que ce jeu de données comprends 25 bureaux de vote, alors qu'il y en avait 28 en 2024. J'ai quand même essayé de reproduire les 25 bureaux sur la carte, mais ils se positionnent dans des quartiers qui ne correspondent pas au lieu où ils devraient être (voir PJ). Je vois deux explications:
- la carte des bureaux de vote de Colomiers a été totalement refondée et cela n'a pas été pris en compte dans le jeu de données
- il y a une mauvaise correspondance entre le bureau de vote et son emplacement géographique réel, à l'instar de mon autre problème pour les 586 communes de la Haute-Garonne.

[Stéphane.zip](https://github.com/user-attachments/files/17023618/Stephane.zip)
[Carte_BureauxVotesA5_mars_2024.pdf](https://github.com/user-attachments/files/17023619/Carte_BureauxVotesA5_mars_2024.pdf)
