### ISSUE TITLE
Non correspondance des communes sur la carte

### ISSUE THREAD

**Issue by DAVIDGOUARD** [riatelab/magrit#139]
Bonjour,
J'ai téléchargé les fichiers relatifs au découpage par communes du département de la Haute-Garonne (voir PJ). Or, lorsque j'enrichis mon fichier excel avec des données électorales pour chaque commune, le report sur la carte ne correspond pas à l'emplacement géographique des communes. Je ne vois pas d'où vient le problème. Merci pour votre aide. 

[communes-haute-garonne.zip](https://github.com/user-attachments/files/17017055/communes-haute-garonne.zip)

**Comment by mthh** [comment]
Bonjour,

Pourriez-vous me décrire plus précisément la procédure que vous avez suivi ?
(et/ou éventuellement me fournir également le fichier excel correspondant ?)

**Comment by DAVIDGOUARD** [comment]
Bonjour,

Tout d'abord, je vous remercie pour votre réactivité. 

J'ai ajouté 4 colonnes au fichier Excel des 586 communes de Haute-Garonne :
- score de la liste RN en % des voix exprimées aux européennes de 2019
- score de la liste RN en % des voix exprimées aux européennes de 2024
- ratio entre les deux scores
- différence en points entre les deux scores
- 
Or, sur la carte créée sur Magrit, les résultats ne correspondent pas du tout à la position géographique réelle des communes (voir notamment Toulouse, la commune avec la plus forte superficie).
Je ne parviens pas à vous adresser le fichier excel modifié car le format n'est pas accepté par la plateforme (voir copie d'écran en PJ).
Merci

![copie écran vote RN européennes 2019](https://github.com/user-attachments/assets/0177887a-6749-4ed5-8492-c672047bd98d)
![copie écran fichiers Haute-Garonne](https://github.com/user-attachments/assets/c08abedb-4682-4860-9819-15a6d0042b97)

**Comment by mthh** [comment]
Mes excuses pour le délai de réponse sur le suivi de cette issue.
Je me permets de clore cette issue car ça ne semble pas être lié à un bug (mais plutôt à des difficultés de réalisation d'une carte).
Si vous souhaitez me contacter directement, vous trouverez mon adresse email sur la page https://magrit.cnrs.fr/contact-us.html, je pourrai essayer de vous guider dans la réalisation de votre carte si vous le souhaitez.
