### ISSUE TITLE
Modification du typage des champs

### ISSUE THREAD

**Issue by ThibaultLeCorre** [riatelab/magrit#143]
Salut,

Un "bug" a été constaté par mes étudiants et celui-ci arrive de manière récurrente et aléatoirement. Il arrive que les champs ne peuvent pas être changés en d'autres types que "catégoriel" ou "inconnu". Pour un même jeu de données le typage impossible d'une colonne en ratio ou en stock n'est pas systématique, tant sur la version locale que sur la version en ligne, ce qui suscite mon incompréhension pour isoler l'origine du problème. J’imagine que ce n'est pas la première fois que cette issue est relevée mais je n'ai pas trouvé de trace.
Merci !

**Comment by mthh** [comment]
Merci pour ce retour !

Je n'ai pas eu de retour de ce type jusqu'ici.
Effectivement, il est parfois impossible de typer une variable en "ratio" ou en "stock", mais c'est (normalement !) toujours parce que la colonne contient des valeurs non-numériques.
Et lorsque qu'il est impossible de typer une variable comme "identifiant" c'est parce que celle-ci contient des valeurs en double (non-unique). Ne laissant donc plus que les types "catégoriel" et "inconnu".

Serait-il possible que tu partages un jeu de données d'exemple permettant de déclancher ce bug ?

Merci d'avance !

**Comment by ThibaultLeCorre** [comment]
Alors tu viens sûrement de me donner la solution. Certaines absence de valeurs sont traduites par "NA". Je te mets le .csv qui pose problème. Mais je n’arrive pas à expliquer que l'erreur ne soit pas systématique.  
[emplois_airesdiffusion.csv](https://github.com/user-attachments/files/17330694/emplois_airesdiffusion.csv)
Merci beaucoup !

**Comment by mthh** [comment]
Merci, je vais investiguer sur la base de ton fichier, car normalement il y a du code (précisément ici : https://github.com/riatelab/magrit/blob/master/src/helpers/formatConversion.ts#L144-L146) pour gérer les valeurs NA dans les colonnes qui contiennent valeurs numériques + NA (pour remplacer les NA par la valeur `null` en JavaScript et permettre ensuite que la variable soit reconnue comme une variable numérique avec valeurs manquantes).

Peut-être que ça ne fonctionne pas comme prévu (j'ai corrigé un autre bug dans la détection du type des champs cette semaine, peut-être que j'en ai introduit un nouveau au passage...).

**Comment by mthh** [comment]
C'était bien une erreur introduite hier ; le fait que ça ne soit pas systématique dépendait de si la colonne contenait ou non des zéros...  :facepalm:
(sur ton jeu de données, ça fonctione pour la variable `POPACT` où les NA sont correctement remplacés par des valeurs nulles, et où la variable est correctement typée comme un nombre, mais pas pour les autres variables).

Je corrige ça et je publie une nouvelle version très prochainement, désolé pour le désagrément !

**Comment by ThibaultLeCorre** [comment]
Super, merci Matthieu ! 
Bonne fin de journée, 
Thibault 


De: "Matthieu Viry" ***@***.***> 
À: "riatelab/magrit" ***@***.***> 
Cc: "Thibault Le Corre" ***@***.***>, "Author" ***@***.***> 
Envoyé: Jeudi 10 Octobre 2024 12:16:17 
Objet: Re: [riatelab/magrit] Modification du typage des champs (Issue #143) 





C'était bien une erreur introduite hier ; le fait que ça ne soit pas systématique dépendait de si la colonne contenait ou non des zéros... \uD83E\uDD26 
(sur ton jeu de données, ça fonctione pour la variable POPACT où les NA sont correctement remplacés par des valeurs nulles, et où la variable est correctement typée comme un nombre, mais pas pour les autres variables). 

Je corrige ça et je publie une nouvelle version très prochainement, désolé pour le désagrément !

**Comment by mthh** [comment]
C'est corrigé et publié.
Par défaut les champs `EMP0`, `EMP1`, `EMP7` et `EMP8` restent typés en "catégoriel" par défaut, mais il est bien possible de changer le type en "stock" ou "ratio" (puisque que le type numérique est bien reconnu en interne, cf. screenshot).

![type](https://github.com/user-attachments/assets/8676665f-64ca-4488-9c30-0dd645b996b1)

S'ils sont quand même classés en "catégoriel" par défaut c'est parce que Magrit regarde s'il y a de nombreuses modalités qui se répètent et, si c'est le cas, en déduit que c'est probablement des catégories plutôt qu'un stock par exemple.

N'hésite pas en cas de nouveau problème !

**Comment by ABOISS** [comment]
Bonjour,

J'ai un problème similaire.

Lors de l'import du tableau seul, le typage des données se fait correctement : 

![Image](https://github.com/user-attachments/assets/c60b0bdc-f742-4a98-a43d-a9bf099a287a)

Une fois la jointure faite avec le fond de carte, deux des colonnes ne peuvent plus être passées en Stock. Elles contiennent toutes les deux des valeurs nulles donc je pense que le problème vient de là mais je n'arrive pas à le résoudre : 

![Image](https://github.com/user-attachments/assets/3a984ced-6a3c-4a0f-9f3d-829c957762f6)

Merci d'avance pour votre aide.
AB

**Comment by ABOISS** [comment]
Voici les fichiers en question (exercice pour des L2)

[Villes-USA.zip](https://github.com/user-attachments/files/19208207/Villes-USA.zip)

[04_Villes_M.xlsx](https://github.com/user-attachments/files/19208188/04_Villes_M.xlsx)

**Comment by mthh** [comment]
Merci pour votre retour.
Utilisez vous bien la dernière version disponible en ligne ?

Je n'arrive pas à reproduire votre problème avec vos données (comme en témoigne la vidéo test ci-dessous) :

https://github.com/user-attachments/assets/1fff6410-61ed-47e4-a907-e02b0cc63ed2

J'ai testé avec Firefox et Chromium (avec GNU/Linux).
Pourriez-vous me dire avec quel navigateur / OS vous travaillez afin que j'essaie de reproduire le bug en question.

**Comment by mthh** [comment]
Entendu, merci.

Quand vous dite que ça fonctionne avec l'ancienne version, connaissez vous le numéro de version de celle avec la quelle ça fonctionnait pour m'aider à investiguer ? (ou vers quelle époque ça fonctionnait sinon)

**Comment by ABOISS** [comment]
J'ai téléchargé le tableau que je vous avais envoyé (car j'ai modifié le mien 50 fois depuis) et ça semble fonctionner... 
J'ai refait l'essai avec tous les fonds de carte (car je chargeais les Etats également) et ça fonctionne aussi.
Un mystère (mais heureux).

Je prépare l'exercice pour mes 4 collègues donc je vais leur envoyer ces données et leur demander de faire l'essai de leur côté.

J'ai testé sur la version disponible en bas de page quand on ouvre Magrit : 

![Image](https://github.com/user-attachments/assets/167e2c27-732d-43b2-a06b-55f88c84ea26)

**Comment by ABOISS** [comment]
Merci pour votre aide (magique ?) !

**Comment by mthh** [comment]
> J'ai téléchargé le tableau que je vous avais envoyé (car j'ai modifié le mien 50 fois depuis) et ça semble fonctionner...

OK, tant mieux effectivement :)

N'hésitez pas à reposter sur ce fil si le problème se représentait à nouveau (ou à ouvrir une nouvelle *issue* en cas d'autre problème !).

> J'ai testé sur la version disponible en bas de page quand on ouvre Magrit 

Merci (je ne savais pas si vous faisiez référence à une précédente release de Magrit v2 ou à Magrit v0).

> Merci pour votre aide (magique ?) !

Si seulement... !
Au plaisir, n'hésitez pas en cas de besoin.

**Comment by ABOISS** [comment]
Bonjour,

J'ai le même genre de souci avec une autre table : le typage des données se fait mal sur une colonne de pourcentages et ne peut pas être modifié car seuls les types "catégoriels" et "inconnus" sont disponibles. ça a lieu sur le fichier .xslx et le fichier .csv mais sur ce dernier une colonne invisible peut être typée avec tous les choix (alors qu'en xlsx les champs ne sont pas nommés). 

Voici les fichiers : 

[Data-UK.csv](https://github.com/user-attachments/files/19289785/Data-UK.csv)
[Data-UK.xlsx](https://github.com/user-attachments/files/19289784/Data-UK.xlsx)
[UK_Local_Authority_Districts_GEN.json](https://github.com/user-attachments/files/19289783/UK_Local_Authority_Districts_GEN.json)

Merci d'avance,
AB

PS : sur l'ancienne version de Magrit (celle d'avant 2024), ça marche TB.

**Comment by ABOISS** [comment]
Merci pour votre réponse et merci d'avance !

Pour les titres de colonnes, nous avons en effet remarqué avec les étudiants que, de manière assez aléatoire nous semblait-il, les titres de colonnes sautent. On s'en est toujours accommodé cela dit ;-).
Dans le cas présent le fichier est un copier-coller (+ suppression des lignes et colonnes inutiles) depuis un tableau du NHS anglais. Je vais voir si ça change quelque chose de renommer les colonnes.

AB

**Comment by mthh** [comment]
Bonjour @ABOISS,

J'ai mis en ligne aujourd'hui une nouvelle version de Magrit (2.3.0) contenant des correctifs pour les 2 points discutés précédemment :

- la suppression des colonnes et lignes vides à la fin du fichier CSV (ce qui permet à votre fichier data-UK.csv de s'ouvrir sans colonnes supplémentaire, et sans entités vides à la fin du fichier, ce qui réactive la possibilité de typer la colonne souhaitée en "ratio", c'est d'ailleurs le type qui est détecté par défaut)

- la correction du problème de reconnaissance de la ligne d'entête dans le fichier XLSX (ce qui permet que la ligne d'entête de votre fichier data-uk.xlsx soit bien "Local Authority - Area code - Percentage of children FYE 2023" et qui permet que la colonne que vous souhaitiez utiliser soit bien typée en "ratio")
