### ISSUE TITLE
cartes lissées

### ISSUE THREAD

**Issue by batardy** [riatelab/magrit#144]
Bonjour,
j'ai un fichier shape. Quand je l'ouvre sur l'ancienne version de Magritt pour faire des cartes lissées je vois apparaitre la totalité des variables de la table. Quand j'ouvre dans la nouvelle version je n'ai pas toutes les variables disponibles pour les cartes lissées. 
[polygones.zip](https://github.com/user-attachments/files/17398665/polygones.zip)

Merci.
Christophe Batardy

**Comment by batardy** [comment]
Bonjour, 
Merci pour la vidéo.
Le "problème" de Magritt c'est qu'il permet de réaliser des traitements que d'autres logiciels réalisent moins bien en terme de rendu. C'est le cas des cartes lissées.

Bien cordialement,
Christophe Batardy
CNRS ENS

**Comment by mthh** [comment]
Merci pour votre retour et pour le compliment sur la qualité des cartes lissées ;)

Je clos cette *issue* si c'est résolu mais n'hésitez pas si vous rencontrer un autre problème.

Bien cordialement,

Matthieu
