### ISSUE TITLE
Bug siteweb : footer cache la fin de la page

### ISSUE THREAD

**Issue by Rom1deTroyes** [riatelab/magrit#23]
Le Bonjour !
Pas sûr que se soit le bon lieu pour ça, mais j'ai un problème d'affichage du site http://magrit.cnrs.fr/

Sous Firefox, le footer recouvre le bas de la page, cachant la fin des paragraphes du bas (*RIATE*, ...) :

![magrit cnrs fr-xs](https://cloud.githubusercontent.com/assets/8625432/24057316/3e656660-0b47-11e7-9619-7184471d4ace.png)
![magrit cnrs fr-l](https://cloud.githubusercontent.com/assets/8625432/24057312/3e61f764-0b47-11e7-8068-559d1d4116cf.png)
![magrit cnrs fr-m](https://cloud.githubusercontent.com/assets/8625432/24057315/3e65b606-0b47-11e7-9037-bd6683db4464.png)

En essayant plusieurs largeur, on a des formats qui fonctionnent :

![magrit cnrs fr-s](https://cloud.githubusercontent.com/assets/8625432/24057313/3e6342a4-0b47-11e7-8eed-8234de8ae7b2.png)
![magrit cnrs fr-xl](https://cloud.githubusercontent.com/assets/8625432/24057314/3e63f528-0b47-11e7-8a44-ce735bfbdfcf.png)

Config : Debian 8 stable / FireFox ESR 45.7.0 / Pas de module ou autre.
Je peux donner plus de détails / faire des essais sur demande.

**Comment by mthh** [comment]
Bonjour,

Merci pour votre retour, c'est effectivement le bon lieu pour ça!

C'est noté pour ce problème, cette partie de texte aurait du être accessible grace à une barre de défilement verticale (qui est soit absente, soit trop courte sur vos images); je m'en occupe dans les prochains jours.

**Comment by Rom1deTroyes** [comment]
Le Friday 17 Mar 2017 à 11:43:35 (-0700), mthh a écrit :
> Bonjour,
> 
> Merci pour votre retour, c'est effectivement le bon lieu pour ça!
> 
> C'est noté pour ce problème, cette partie de texte aurait du être
> accessible grace à une barre de défilement verticale (qui est soit
> absente, soit trop courte sur vos images);

Non non, la barre est bien tout en bas, et on ne peut pas aller plus
loin (ni avec la barre de défilement, ni avec les flèches de
navigation...

La fenêtre n'est pas forcément affichée en entier sur les captures
d'écran, mais je peux les refaire et creuser si vos investigations ne
donnent rien (-:

> je m'en occupe dans les prochains jours.

Une piste rapide pour reproduire le problème : jouer avec les largeurs
de page de bootstrap ?

++
    Romain

**Comment by mthh** [comment]
Ça a normalement été corrigé par le commit 79a568d (et sur la version en ligne). N'hésitez pas si vous rencontrez d'autres soucis à l'avenir!
