### ISSUE TITLE
Using Magrit on the Galaxy-E project ?

### ISSUE THREAD

**Issue by yvanlebras** [riatelab/magrit#24]
Hi everyone, I'm on the way to begin the building of a [Galaxy](https://github.com/galaxyproject/galaxy) instance dedicated to [macro-ecology](https://github.com/yvanlebras/Galaxy-E) and I think this can be of interest to think about using Magrit for SIG data visualization instead of or in addition of Leaflet/PostGIS... Maybe we can exchange about this possible enhancement ?

**Comment by mthh** [comment]
Sure, you can reach me at matthieu.viry [at] cnrs [dot] com.

**Comment by mthh** [comment]
Following our discussions this summer, I'm closing this issue for now but don't hesitate to contact us again if needed.
