### ISSUE TITLE
Allow adding several {Sphere}s

### ISSUE THREAD

**Issue by Fil** [riatelab/magrit#26]
In some cases you want a sphere "below", to create the Oceans' colours with a `fill`, and another one "above", to create the contour with a `stroke`.

See for example https://bl.ocks.org/Fil/1ba3e1169472cf9cd59c1e855e05ac62

**Comment by mthh** [comment]
Sure. I have to admit that I could almost instantly reproduce an example were it will be useful to implement your suggestion.

I will work on this that week. Thanks for bringing this issue to our attention!

**Comment by mthh** [comment]
Your suggestion was implemented in the last release (0.3.3)!

![before_after](https://user-images.githubusercontent.com/12172162/27177902-57166106-51c8-11e7-9e94-b9977297fe86.png)

**Comment by Fil** [comment]
merci :)
