### ISSUE TITLE
Confusing docker image

### ISSUE THREAD

**Issue by Fil** [riatelab/magrit#27]
There are two docker images, `magrit/magrit` which is referencing this github repo, and [magrit/magritapp](https://hub.docker.com/r/magrit/magritapp/), which is (??) and might be confusing.

**Comment by mthh** [comment]
Thanks for the edit on the wiki and for raising this issue!

There are indeed two docker images:  
The image quoted on the wiki ([`magrit/magrit`](https://hub.docker.com/r/magrit/magrit/)) is an *Automated Build* (it is automatically built when changes are pushed on github.com/riatelab/magrit) and it should be considered as Magrit *"stable"* version.  
The second image ([`magrit/magritapp`](https://hub.docker.com/r/magrit/magritapp/)) is pushed manually. I would say that it correspond mostly to the Magrit version present on my fork (mthh/magrit) and so online (on magrit.cnrs.fr), notably for testing purposes. That version may be ahead of the github.com/riatelab/magrit directory (and so be ahead of the `magrit/magrit` docker image).

(Currently you might see the `magrit/magritapp` version is lagging behind `magrit/magrit` - I guess I've lost the train on this version one month ago...)

I will explain theses differences in the wiki and rename at least one image to reflect the difference between the "stable" version and the "development" version.

**Comment by mthh** [comment]
Actually I just removed the second image. I guess it's more simple if the (magrit/magrit)[https://hub.docker.com/r/magrit/magrit/] image is the only to stay, up to date with this github repository.
