### ISSUE TITLE
Problem with Grand Paris Municipalities dataset

### ISSUE THREAD

**Issue by rCarto** [riatelab/magrit#33]
*Revenus* data are inconsistent. Correct the values or remove the dataset entirely ?
![image](https://user-images.githubusercontent.com/3041254/48783025-c44c5880-ecdf-11e8-8625-6895c37a32f4.png)

**Comment by mthh** [comment]
Hum... And `Revenus par ménage` were computed using that bogus value...

I vote for correcting the values and keeping theses Grand Paris municipalities as one of our sample dataset. What do you think ?

**Comment by mthh** [comment]
This should be fixed once https://github.com/mthh/magrit/commit/471d2703c28313f608b4cade32e0f700279d4ffe will be merged.
I rolled back to a previous version of the file (as it was on https://github.com/riatelab/magrit/commit/4eba615d07ebe90a199abbcf63ea0819a5219928) and recomputed the `revenus_par_menage` variable.

**Comment by mthh** [comment]
Fixed in #34 (v0.8.10)
