### ISSUE TITLE
Utilisation des templates cartographiques proposés, encarts DOM

### ISSUE THREAD

**Issue by aschoenauer-sebag** [riatelab/magrit#37]
Bonjour,

Nous aimerions pouvoir utiliser les templates proposés qui sont très pratiques (http://magrit.cnrs.fr/, bas de la page) ; malheureusement lorsque l'on importe un fond de carte principal type shapefile, les DOM du shapefile ne sont pas localisés sur les encarts prévus pour les DOM du template. Pourriez-vous nous indiquer une solution, par exemple nous fournir les coordonnées des polygones DOM dans le template afin que nous modifiions nos shapefiles ?

Merci !
Alice

**Comment by mthh** [comment]
En effet les DOM ne sont pas réelement reprojeté à la volée; leurs positions ont été inscrites en dur dans les fichiers que fournissont pour ces templates (c'est la principale limites de ces templates avec boxes).

Vous pouvez toutefois télécharger les couches relatives à chaque template en allant dans le menu "Export de la carte" : 

![Screenshot_2019-03-11 Magrit](https://user-images.githubusercontent.com/12172162/54125782-3e772900-4406-11e9-8127-aff4427ac0e7.png)

Vous pourrez ainsi récupérer les couches communes, départements, régions dont les DOM sont déplacés pour coller avec notre template; ainsi que le tracé des boxes bien entendu.

**Comment by aschoenauer-sebag** [comment]
Merci beaucoup pour votre réponse rapide, on teste et on vous dit (a priori ça devrait marcher :).

Alice
