### ISSUE TITLE
Joining data and basemap at the commune scale

### ISSUE THREAD

**Issue by aschoenauer-sebag** [riatelab/magrit#38]
Hi,

We are trying to plot data at the commune level. We're easily loading the template from http://magrit.cnrs.fr as well as our data ; however when attempting to join COMMUNES and our data using INSEE codes MAGRIT displays "Loading results" and never finishes.

Thanks for your help,
Alice

**Comment by mthh** [comment]
Thanks for the report !

Indeed, it's a bug in Magrit. When the number of entities is particularly high, the join is not done in the main thread but in a webworker (in which the error is encountered...).

I pushed a fix but CI is causing us some troubles right now and I may have to merge some others stuff before I can bring this fix back to the master branch (so I will close this issue once merged on master and deployed on magrit.cnrs.fr).

**Comment by aschoenauer-sebag** [comment]
OK, thanks for your quick reply. Looking forward to the merge on master (any idea if this will be sooner, or rather later? :).

Thanks,
Alice

**Comment by mthh** [comment]
Normally during the next week ...!

We do not share offices with @rCarto anymore and we have a few things to work on before publishing a new version :)

**Comment by aschoenauer-sebag** [comment]
Great, thanks for keeping us updated :)
