### ISSUE TITLE
Suggestion template proposé

### ISSUE THREAD

**Issue by VivienGuerin** [riatelab/magrit#43]
Bonjour,

Je voulais savoir si c'était possible de rajouter un template avec les collectivités d'outre-mer dans des encarts ainsi qu'un template avec un zoom sur l’Île-de-France dans un encart. 

Merci.

**Comment by mthh** [comment]
Bonjour et merci pour vos suggestions !

D'un point de vue technique c'est en effet possible :
- dans le premier cas comme pour nos templates avec DROM actuels (après avoir choisi la taille et la position souhaitée il faut faire plusieurs transformations afin qu'ils s'affichent comme s'ils étaient chacun dans leurs projections locales UTM adaptées alors que la couche est en Lambert 93)
- dans le second cas ça pourrait demander quelques changements dans le code si on veut que les entités situées en ile de France soient à la fois affichées dans un encarts et sur le fond de carte.

Dans les deux cas, je trouve personnelement que c'est un bonne idée.

Est-ce que ce sont déjà des templates que vous avez préparé ? 

Je ne vais malheureusement pas avoir de temps à y consacrer prochainement (mais je laisse les autres membres du @riatelab se prononcer). En effet je trouve que la création de template carto de ce type demande au final pas mal de boulot et pose différents types de questions : choix de la source des données, généralisation du tracé, choix de la taille et de l'emplacement des encarts (ces 2 derniers points pouvant être l'objet de nombreux débats..), préparation des différentes couches associées (pays voisins, etc.), documentation des opérations effectutées, etc..

**Comment by rCarto** [comment]
Bonjour, 
Si vous avez déjà créé ce template (sous forme de fichier projet Magrit) nous pouvons envisager de le proposer sur la page d'acceuil de l'appli.

**Comment by VivienGuerin** [comment]
Bonjour,
Malheureusement je n'ai pas le template.

**Comment by ArmelVidali** [comment]
Bonjour,

J'ai eu le meme besoin que vous (pouvoir réaliser des cartes composites avec des encarts) et ai réalisé un outil avec Leaflet pour construire visuellement ce genre de carte en déplacant les entités à la main.

C'est une première version beta mais vous pouvez la tester et me faire un retour si vous trouvez ca utile / avez des améliorations à suggérer : https://armelvidali.github.io/inset_map_maker/  (lien du repo : https://github.com/ArmelVidali/inset_map_maker). On peut faire des encarts avec n'importe quel shape de la carte (y compris métropole)

![image](https://github.com/riatelab/magrit/assets/84096571/e944f96f-e92b-4db9-92b7-87e4aa915934)


Attention : l'outil ne fonctionne qu'avec des json/geojson contenant uniquement des polygones (pour l'instant)


J'ajoute que depuis cette suggestion le labo riate à publié un repo pour générer ce genre de carte en R : https://github.com/riatelab/map-templates
