### ISSUE TITLE
Problème de rendu svg

### ISSUE THREAD

**Issue by vinber** [riatelab/magrit#50]
Quand je veux exporter certaines projections, cela ne semble pas fonctionner.

# Exemple

- un nouveau projet
- Sélection d'un fond de carte d'exemple (world_countries_data)
- dans les choix de projections, choisir plus d'option, sélectionner lambert93, reprojetter
- cela fonctionne
- export de la carte en svg 
- le fichier est vide

Cet exemple est également vérifié avec la projection conique conforme

Firefox 68 / Ubuntu 18.04

**Comment by mthh** [comment]
I can't confirm this bug either (Chromium: 104.0.5112.81). 

In general, for bugs of this type, it can be nice to provide:
- the project file, allowing us to recreate the same map (the button with a floppy disk, on the right of the navigation bar),
- possibly, when it concerns a svg or png problem, the exported file.
