### ISSUE TITLE
Pouvoir masquer le contour des polygones

### ISSUE THREAD

**Issue by ericemc3** [riatelab/magrit#61]
J'aimerais, avec une carte choroplèthe (France par commune pour situer), pouvoir masquer complètement le contour des communes (pas de stroke) pour gagner en lisibilité et en fluidité.
Mais si je fixe l'épaisseur de la bordure à 0 , et même l'opacité de la bordure à 0, 
![image](https://user-images.githubusercontent.com/17407796/98678837-7105c180-235f-11eb-9a6f-6b3a024a60dc.png)

j'ai toujours un contour visible :
![image](https://user-images.githubusercontent.com/17407796/98678756-57fd1080-235f-11eb-8ba7-8cd2c0427cbd.png)

**Comment by mthh** [comment]
En effet, merci pour ce retour de bug.

En réalité les bordures sont bien absentes (en terme de propriétés CSS/SVG), il me semble que le petit espace qu'on voit entre les polygones est du à l'anti-aliasing qu'on peut contrôler avec la propriété SVG [shape-rendering](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/shape-rendering).

En attendant qu'un correctif soit appliqué à la version de Magrit qui est en ligne et si vous le souhaitez, vous pouvez essayer la procédure suivante :
- ouvrir les outils du développeur de votre navigateur (en appuyant sur F12) lorsque vous êtes sur la page de Magrit
- aller dans l'onglet "console"
- saisir la commande suivante dans l'invite de commande qui est affichée : 
`document.querySelector('svg#svg_map').setAttribute("shape-rendering", "crispEdges")`.
- fermer les outils du développeur en appuyant à nouveau du F12

![console-f12](https://user-images.githubusercontent.com/12172162/98699947-f2694e00-2377-11eb-90f0-0c81ad3b4f97.png)

Normalement vous devriez obtenir le résultat attendus au niveau de l'absence de bordures. En revanche il est possible que certains contours (ou les polices d'écritures) aient un aspect moins net / un peu plus "déchiqueté".

**Comment by mthh** [comment]
@rCarto @neocarto intéressés par une PR qui corrige ce problème ?

Il y a plusieurs stratégies qu'on pourrait adopter :
1. Utiliser la propriété `shape-rendering="crispEdges"` par défaut
2. Utiliser la propriété `shape-rendering="crispEdges"` seulement si l'utilisateur demande à supprimer les bordures (en réglant leur opacité sur 0 et/ou leur épaisseur sur 0), comme ça on conserve l'anti-aliasing dans les autres cas...
3. Ajouter une checkbox dans l'interface pour laisser à l'utilisateur la possibilité de désactiver l'anti-alisasing
4. Un mélange de (2) et (3), on le désactive automatique si l'utilisateur demande à supprimer les bordures, mais on met une checkbox dans l'interface pour le contrôler quand même.

**Comment by ericemc3** [comment]
Je confirme que cela fonctionne, merci pour votre réactivité ! Il faudrait en effet sans doute cibler uniquement les path dans la seule couche concernée, et seulement si la bordure a une opacité de 0 ou une épaisseur 0. Sinon, crispEdges dessine mal les bordures (anti-aliasing absent). Noter que l'option shape-rendering="optimizeSpeed" produit le même résultat (mais je n'ai pas constaté qu'elle était plus rapide que crispEdges). Une case à cocher "masquer contours" serait peut-être plus ergonomique pour activer cette option.

**Comment by ericemc3** [comment]
Si pour une raison ou une autre, shape-rendering posait problème, une alternative pourrait consister à appliquer dans ce cas une couleur de stroke semblable à celle du fill avec un stroke-width faible (0.5 par exemple).

**Comment by mthh** [comment]
Closed by #66 .
