### ISSUE TITLE
Position des symboles proportionnels parfois en dehors du territoire correspondant

### ISSUE THREAD

**Issue by ericemc3** [riatelab/magrit#63]
Les symboles sont semble-t-il dessinés au milieu du rectangle englobant le territoire correspondant, ce qui fait qu'ils peuvent parfois se situer en dehors.
![image](https://user-images.githubusercontent.com/17407796/98975464-6d686b00-2516-11eb-9605-0332f992ccb8.png)

J'ai vu qu'on pouvait les déplacer à la main. Toutefois serait-il possible d'inclure un test pointInPolygon et une correction qui si besoin recentre le symbole dans le territoire associé ?
L'idéal serait de pouvoir prendre en compte une colonne de coordonnées x/y quand elle est fournie dans le fond de carte (par exemple l'IGN fournit la position de la mairie, ce qui est pratique).

**Comment by mthh** [comment]
Effectivement, on utilise le centroide (avec `d3.geoCentroid` / `path.centroid`) pour placer le symbole. Le point n'est pas garanti de tomber dans la géométrie de l'entité en question.

En revanche il est possible de déplacer les symboles individuellement (dans les propriétés de la couche).

Je laisse ouvert car j'aime bien l'idée de l'utilisation d'une liste de coordonnées ! Mais pour l'instant la méthode conseillée va être de déplacer individuellement les points qui ne tombent dans leur polygone d'appartenance...

**Comment by mthh** [comment]
Tout bien réfléchi... je vais prendre votre idée en considération :+1: 

Pour l'instant Magrit n'a pas turf.js dans ses dépendances mais je viens de jeter un coup d’œil au code de [turf-point-on-feature](https://github.com/Turfjs/turf/tree/master/packages/turf-point-on-feature) et il implémente la logique en question (retourner le centroide s'il tombe dans le polygone, ou sinon un autre point à sa surface) donc ça devrait pouvoir être fait à moindre coût..

Merci pour le rappel ;)

**Comment by ericemc3** [comment]
Super. Pour l'anecdote, mais vous connaissez sûrement, Mapshaper, aux objectifs complémentaires et plutôt amont, est pour moi une source continuelle et inépuisable de plaisir et d'inspiration. Il m'arrive de regarder le code et ces questions y sont traitées, en js. 

> -points inner : Create points in the interior of the largest ring of each polygon feature. Inner points are located away from polygon boundaries.

https://github.com/mbloch/mapshaper/wiki/Command-Reference#-points

**Comment by mthh** [comment]
@rCarto un avis sur la question ?

**Comment by rCarto** [comment]
> L'idéal serait de pouvoir prendre en compte une colonne de coordonnées x/y quand elle est fournie dans le fond de carte (par exemple l'IGN fournit la position de la mairie, ce qui est pratique).

Cette solution me gène un peu. Cela implique d'utiliser des couches avec 2 infos géométriques de types différents (point et polygon) de manière explicite et implicite. 
Pour cet exemple je conseillerais plutôt d'utiliser directement la couche des mairies. (d'autant que l'on permet l'import de csv avec des coordonnées.)

Pour la question *point in feature* il faudrait que cela ne soit pas une option (ne pas rajouter de case à cocher) mais le comportement systématique.  
Du coup, je cherche des cas ou il ne serait pas souhaitable d'avoir les points dans les polygones. Pour l'instant je ne vois pas trop.

**Comment by ericemc3** [comment]
Je pense en effet qu'il est toujours souhaitable qu'un symbole soit toujours posé dans le territoire qu'il illustre, ni à l'extérieur, ni dans un trou ;) Et par défaut, si le territoire est un multi-polygone, dans le "ring" le plus vaste.

**Comment by mthh** [comment]
J'ai implémenté un correctif mais je ne suis pas super fan de la position retournée par `pointOnFeature` de turf quand le centroid ne tombe pas dans le polygone (je trouve que le point est trop proche de la bordure du polygone - cela s'explique car en interne c'est calculé avec la fonction `nearestPoint` de turf, sur la base du centroid (à l'extérieur du polygone) et des bordures du polygones).

@Tim que penses-tu du résultat ?

![res](https://user-images.githubusercontent.com/12172162/182628641-b813bd76-7516-4db9-a1df-33f77f203044.png)

Une autre solution serait d'implémenter notre propre "pointOnFeature" avec la logique suivante :
1) calcul du centroid
2) retourne le centroid s'il tombe dans le polygone
3) sinon calcul du pole d'inaccessibilité avec [Polylabel](https://github.com/mapbox/polylabel)
4) retourne le pole d'inaccessibilité

Le point obtenu sera également garantie de tomber dans le polygone et il sera moins proche du bord. Mais un défaut pourrait être que, en fonction de la forme du polygone d'origine, le point pourrait être moins proche de ce qu'on s'imagine être "son centre" (je dois pouvoir trouver un moyen d'illustrer ce cas si besoin)
J'imagine aussi que c'est un peu plus coûteux (mais les polygones pour lesquels le centroid ne tombe pas à l'intérieur ne constituent généralement pas la majorité du jeu de données)

**Comment by rCarto** [comment]
:+1:  `polylabel` ça me semble être le mieux que l'on puisse faire.
