### ISSUE TITLE
Actualisation des données communales

### ISSUE THREAD

**Issue by tdejeans** [riatelab/magrit#72]
Bonjour,

Les données communales datent de 2016, or, des fusions de communes sont depuis apparues et faussent le maillage, savez-vous s'il y aura prochainement une mise à jour ? 

PS : peut-on également espérer les données communales sur Mayotte ?

Bonne journée à vous.
Tom

**Comment by rCarto** [comment]
Bonjour, 
Nous ne prévoyons pas de mise à jour des données d'exemple dans un futur proche. 
Vous pouvez cependant utiliser les fonds de carte diffusés par l'[IGN](https://geoservices.ign.fr/adminexpress). 
Si ces fonds de cartes sont trop lourds, vous pouvez en simplifier les géométries avec des applications comme [mapshaper](https://mapshaper.org/). 
TG.
