### ISSUE TITLE
Carte de liens (flux)

### ISSUE THREAD

**Issue by pitoulegoulut** [riatelab/magrit#73]
Lors de la création d'une carte de lien, impossible de faire une jointure car il y a plusieurs entités avec le même id unique.
Lorsque j'ajoute le fichier CSV d'exemple et que je choisis une représentation sous la forme de liens, l'onglet apparaît dans la barre de gauche mais l'ensemble des fonctionnalités est grisé (désactivé) car il indique ne pas avoir de jointure.
Que faire ? 
Merci

**Comment by rCarto** [comment]
Bonjour, 
Désolé pour le délais de réponse. 
En effet, il ne faut pas faire de jointure au moment de l'import des données.

![Peek 12-05-2022 16-13](https://user-images.githubusercontent.com/3041254/168095941-cba31d1b-5b46-4218-8ee7-ec36888a151c.gif)

**Comment by pitoulegoulut** [comment]
Bonjour,

Je vous remercie pour ce retour.

C’est bien ce que je tente de faire, mais le menu de cartographie de flux est grisé bien que mes données soient importées.

Bien à vous,

 

 

De : Timothée Giraud ***@***.***> 
Envoyé : jeudi 12 mai 2022 16:16
À : riatelab/magrit ***@***.***>
Cc : pitoulegoulut ***@***.***>; Author ***@***.***>
Objet : Re: [riatelab/magrit] Carte de liens (flux) (Issue #73)

 

Bonjour,
Désolé pour le délais de réponse.
En effet, il ne faut pas faire de jointure au moment de l'import des données.

 <https://user-images.githubusercontent.com/3041254/168095941-cba31d1b-5b46-4218-8ee7-ec36888a151c.gif>

**Comment by mthh** [comment]
Bonjour @pitoulegoulut 

Serait-il possible que vous partagiez vos données afin que je puisse essayer ? (pour voir s'il s'agit d'un bug par exemple, ou pour vous offrir une aide + détaillée sinon).
Mon adresse email : matthieu.viry@cnrs.fr.

Bien cordialement
