### ISSUE TITLE
add buffer option for labels layer

### ISSUE THREAD

**Issue by rysebaert** [riatelab/magrit#79]
![magrit](https://user-images.githubusercontent.com/17565776/177576251-6810b7b8-6429-447a-b1b4-09ef119a9805.PNG)

**Comment by mthh** [comment]
Thanks, that's a good idea that I will implement !

As a note, I also have the feeling that the buffer added around the title and the buffer added around the text annotations (that can be added individually to the map) are not the same size by default.

It would be nice if, by implementing this feature, we could take the opportunity to make the default text buffer similar on the 3 types of text that can be added: title, text annotation and label layer.

**Comment by mthh** [comment]
Hopefully, this will also go with the following improvements:
- choice of border thickness for the buffer of the text annotation (this option existed only for the title),
- a way better rendering of the buffer for both title and text annotation (I find that the rendering of the title is a bit ugly at the moment at some sizes),
- better detection of the currently used font when reopening the option menu (sometimes the font was not detected correctly after reopening the project file, so the current value of the font selection menu was empty).
