### ISSUE TITLE
Waffle Map not locating

### ISSUE THREAD

**Issue by robinsonlucas** [riatelab/magrit#87]
When projecting a waffle map, representation is send in the upper left corner of the map instead of being located on the basemap. The jointure is not the problem as the stock representation is working.

![exemaple](https://user-images.githubusercontent.com/38052766/188937325-3478a86c-f709-4a79-8f20-2e7ffea2b77b.png)

**Comment by mthh** [comment]
Thank you for your feedback!
It was indeed a bug.

A fix has been made in commit 3b43a62 and it is included in version 0.9.2.

It is already online on [magrit.cnrs.fr](https://magrit.cnrs.fr) (you may need to refresh the page if you are still on version 0.9.1 - you can see the version number by clicking on the question mark at the top right of the page https://magrit.cnrs.fr/module).
