### ISSUE TITLE
Problem with Geopackage import on Windows

### ISSUE THREAD

**Issue by mthh** [riatelab/magrit#91]
~~Should a future release support the import of geopackage files?~~
~~That would keep up with current practices.~~

~~From a technical and UX point of view I think it's not too complicated, we would only take the vector files contained in the geopackage and ask the user which of these layers (if any) is the target layer (and so import all the others as layout layers).~~

~~To go further we could also ask the user which layers to import among the vector layers contained in the file...~~

EDIT: For those having issues with GeoPackage on the version 2 of Magrit, the July 2024 discussion starts [here](https://github.com/riatelab/magrit/issues/91#issuecomment-2210816591).

**Comment by neocarto** [comment]
Yes, importing gpkg seems a very good idea. Question : should the development of this feature has to be done within the code of Magrit or should we deport the code to an external library that is able to handle more than one format. To have scanned different possibilities (https://observablehq.com/@ambassadors/geographical-features-imports), i think that this kind of lib would be useful.

**Comment by mthh** [comment]
So far all layers are sent to the server (where they are transformed to WGS84, have their column names cleaned up if needed, etc.) so I think it's pretty easy to keep doing that for now (since we have GDAL/OGR on the server).

However, following some discussions we had on Magrit, it is possible that we will move all these stuff client-side in the future.
In such a case I agree that it would be interesting to have a lib that would manage all the format we support (for magrit and for the community).

I would be happy to pool our efforts towards a library like you mention.
Maybe we could create a repository and discuss there the potential design of such a library and the options we have?

I don't know if you already use [gdal3.js](https://github.com/bugra9/gdal3.js). It's a heavy JS dependency (since it contains wasm code) but I've had pretty good experiences with it, and it's normally pretty robust for handling everything that's encoding, reference coordinate system, transformation, etc.

**Comment by mthh** [comment]
> I would argue against importing all other layers as layout layers (it could be a lot of layers, or irrelevant layers ). I would directly go further as you suggest.

Makes sense ! Will do this way !

**Comment by mthh** [comment]
I have an implementation in progress but it is currently blocked by #99.

**Comment by mthh** [comment]
Fixed by commits 0e59282 to 61a8920. It will be released in the very next minor release (v0.12).
Turns out #99 wasn't *that* blocking and it will be handled later.

**Comment by RCura** [comment]
Seems this is not working at the moment : I tried loading different (and simple) geopackages files, and all fails (no error displayed, just the importer keeping running at the "Analyse du jeu de données" step forever).

Here's the actual error in the console (firefox) : 
``` 
Uncaught (in promise) TypeError: f2.info.layers is undefined
```

(in chrome it's less informative)
``` 
TypeError: Cannot read properties of undefined (reading 'forEach')
```

N.B. : same error in local version (windows) and site-deployed version

**Comment by RCura** [comment]
@mthh : not sure if that was the good thing to do replying in a closed issue, but here's a problem with geopackages

**Comment by mthh** [comment]
Can you share your geopackage (or a geopackage that allows to reproduce the issue) by email ?

I'm unable to reproduce it (cf. my screenshot).

![Capture du 2024-07-05 15-08-51](https://github.com/riatelab/magrit/assets/12172162/96e80ddd-1481-467d-8441-0b16affeb5ca)

> not sure if that was the good thing to do replying in a closed issue

No problem, I'm reopening the issue for now.

**Comment by RCura** [comment]
Tried with some of mine (that I can't share), and then confirmed with this one : 

[](https://www.data.gouv.fr/fr/datasets/etablissements-publics-de-cooperation-intercommunale/)
-> EPCI 2023 (gpkg)

Tried it with QGIS of course, and it works as expected.

N.B. I only tested with single-layers gpkg, might be the problem ?

**Comment by mthh** [comment]
> that I can't share

No problem ;)
Thanks for providing another problematic dataset!

> N.B. I only tested with single-layers gpkg, might be the problem ?

It should not!

Having had a look, the problem may be more complex than I expected, as the EPCI 2023 dataset in Geopackage works on my machine (GNU/Linux + Firefox or Chromium).

I'll try investigating on a Windows machine soon...

Thanks for reporting this issue!

**Comment by mthh** [comment]
It's finally fixed ;)
