### ISSUE TITLE
Modality in legend but not on the map

### ISSUE THREAD

**Issue by rCarto** [riatelab/magrit#93]
In a colored (by category) proportional symbols map if a spatial unit has a 0 or no value in the 1st field there is no circle drawn. If this unit is the only unit with a specific modality then the modality appears in the legend but not on the map. 

In the linked project see Antarctica (with special case of unnamed or "" modality, but that's should not be relevant).
[magrit_project(4).zip](https://github.com/riatelab/magrit/files/9723901/magrit_project.4.zip)

**Comment by mthh** [comment]
Nice catch !

Je vais m'occuper de ne plus faire apparaître dans la légende les entrées dont ne relève aucune entité sur la carte.

Par ailleurs, dans une carte de typologie seulement (valable aussi pour typo + symbole of course) actuellement on regroupe les entités qui ont `null` (ou `""`) dans une catégorie non-nommé. Comme dans ton exemple (même si là ça n'aurait pas du apparaître), ça donne un vide dans la légende. Est-ce qu'on ne devrait pas renommer cette catégorie vide en quelque chose comme "Catégorie non-nommée" / "Unnamed category" ? Ça forcerait peut-être aussi l'utilisateur à changer le nom pour quelque chose qui lui convient ?

**Comment by rCarto** [comment]
Plutôt d'accord avec ça. 
Je mettrais plus "Catégorie indéfinie" / "Undefined category" que non nommée.
Et je ne rajouterai pas une option supplémentaire. Dans l'idée d'inciter l'utilisateur à nettoyer ses données :-).
