### ISSUE TITLE
Mushroom map to have another portrayal that works with 2 stocks?

### ISSUE THREAD

**Issue by mthh** [riatelab/magrit#95]
As in bertin.js ?

![mushroom](https://raw.githubusercontent.com/neocarto/bertin/main/img/mushroom.png)

**Comment by rCarto** [comment]
I'll let others reply, but it looks like weird pie charts to me :smile:.

**Comment by mthh** [comment]
Indeed :laughing: 
I'm not specifically attached to adding this method, I was thinking about it more from a pedagogical point of view (*having methods that allow to represent 2 comparable stocks* - but we already have the waffles).

I'll leave the issue open for a bit to see if other people have an opinion.

**Comment by mthh** [comment]
Added in the v2.
